### ISSUE TITLE
#pybr2023-online

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2023-org#142]
(Estou atualizando essa issue ao poucos)

### Descrição

- [x] #150
- [x] https://github.com/pythonbrasil/pybr2023-org/issues/149

**Comment by Camilotk** [comment]
Olá @rougeth ! Camilo aqui. Junto com o  Mateus estou focado em ajudar nessa frente.

Algumas sugestões extras:
- Precisamos de pessoas para ajudar no acesso e suporte ao Discord, para nós isso é algo rotineiro, mas existe um grande número de pessoas que não é acostumada com a Plataforma, além dos que já conhecem e por um motivo ou outro vão precisar de ajuda. Tem pessoas que se voluntariaram a isso.

**Comment by rougeth** [comment]
@Camilotk concordo com tudo que você falou :)

Precisamos sim juntar as pessoas voluntárias para o evento online e definir como vai ser o trabalho durante o evento.

Podemos usar o projeto aqui do Github mesmo para as tarefas: https://github.com/orgs/pythonbrasil/projects/5/views/12, qualquer tarefa com a tag `online` vai aparecer por lá. Vou ficar mais presente agora nessas últimas semanas pré evento.
