### ISSUE TITLE
Criar evento no eventbrite para ingressos de palestras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#17]

**Comment by marceloandriolli** [comment]
Olá @cecivieira !

Já mexi com eventbrite para ingressos da Python Sul de Floripa e também da Python Sul de Jaraguá em SC. Para que eu posso criar um evento dentro do eventbrite é preciso que o perfil da APyB como organização me adicione como membro da organização então consigo associar a venda dos ingressos a conta do banco da APyB. Além disso também preciso das seguintes informações:


- Endereço completo do evento
- Política de reembolso 
- Tipos, quantidade e valores dos ingresso.
- Texto descritivo sobre o evento.
- Arte em formato de banner para colocar na pagina de venda dos ingressos

Segue o link de inscrição a ultima PyBr, só para termos uma noção ou referência: https://www.eventbrite.com.br/e/python-brasil-2022-registration-356802725557?aff=ebdsoporgprofile

**Comment by cecivieira** [comment]
@marceloandriolli no eventbrite já está cadastrada a conta da APyB e também temos um formulário para coleta de informações, que está sendo usado nos últimos anos.

A ideia é que esse formulário também seja usado esse ano, assim manteremos um padrão na coleta de dados socioculturais importantes para análise do perfil do público. 

O texto também pode ser considerado o do ano anterior, com algo de atualização.

Acredito que o que está faltando é a definição de quantidade, tipo e preço dos ingressos. (@adrinomargarin poderia fornecer essas informações?)

A arte do banner é de minha responsabilidade solicitar. Coloco-a aqui, quando tiver pronta.

**Comment by cecivieira** [comment]
Feito:
https://www.eventbrite.com.br/e/python-brasil-2023-registration-576537738897
