### ISSUE TITLE
Selecionar fotos para identidade visual

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#23]
Selecionar fotos dos anos anteriores - [Flirck](https://www.flickr.com/photos/pythonbrasil/) - para ajudar na criação da identidade visual.

---- Pontos importantes ----
- Diversidade de gênero, corpos, raça e sexualidade

**Comment by anadulce** [comment]
Pasta para fotos selecionadas:
https://drive.google.com/drive/folders/1OPel_b4DEILElOOL37w_jMcdSA0M8Jo-?usp=share_link

**Comment by anadulce** [comment]
Flickr:
https://www.flickr.com/photos/pythonbrasil/albums

**Comment by tiidadavena** [comment]
Qual a resolução das fotos é a que deve ser utilizada? Tô baixando no tamanho "Large" (2048 x 1365).

**Comment by anadulce** [comment]
Eu baixei no maior que tinha, só porque parecia uma boa ideia :)

**Comment by cecivieira** [comment]
@anadulce já tem foto suficiente? Já pode fechar essa issue?

**Comment by cecivieira** [comment]
Feito
