### ISSUE TITLE
Consertar workflow das issues de reunião

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#24]
### Descrição
Foi replicado, da organização de 2022, o [workflow para criação automática das pautas das reuniões](https://github.com/pythonbrasil/pybr2023-org/blob/main/.github/workflows/ISSUE_CREATION_WORKFLOW.yml) , no entanto é necessário ajuste. Acredito que no token, mas precisa dá uma olhada com mais atenção para saber se tem outra coisa.

### Requisitos para a atividade ser considerada como concluída
- Action funcionando

**Comment by Perceu** [comment]
Concluido mas ainda falta ajudar alguma coisa nas quebras de linhas no hora da subistituição de texto dentro do corpo da issue
