### ISSUE TITLE
Venda de ingresso

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#37]
### Campanha
*Informe a campanha a qual essa arte faz parte ([lista de campanhas](https://docs.google.com/spreadsheets/d/1BV3IO2GYQg27q8nuznjmZXu5N1aUlOS0k-hv7RWvXbU/edit#gid=0))*
  
### Peça/publicidade solicitada
Abertura da venda de ingressos

### Detalhamento do uso
Divulgaćão da abertura da venda de ingresso do evento principal (palestras e keynotes).

### Data prevista para entrega
27 mar. 23

### Quais informações devem aparecer na arte
Data do evento, local e informaćão do 1. lote

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [ ] Wide (1920x1080)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by Buddhamaniac** [comment]
Hello

**Comment by cecivieira** [comment]
divulgação realizada
