### ISSUE TITLE
Traduzir plano de patrocinio

### ISSUE THREAD

**Issue by Perceu** [pythonbrasil/pybr2023-org#41]
### Descrição
*Necessitamos do plano em ingles e espanhol para enviarmos aos patrocinadores*

### Requisitos para a atividade ser considerada como concluída

*Plano em ingles e espanhol disponibilizado no site*

**Comment by TomCosta** [comment]
Tradução na versão Inglês em parte está **concluída**.
Está pendente:
- Valores/preços em dólar
- Imagens das escritas
- Imagem do gráfico
- Testar no Power Point


<img width="318" alt="Screenshot 2023-04-01 at 16 50 13" src="https://user-images.githubusercontent.com/9824969/229311354-517ede74-da23-4908-9181-d25fdf69671b.png">

<img width="672" alt="Screenshot 2023-04-01 at 16 50 35" src="https://user-images.githubusercontent.com/9824969/229311363-b18adb6b-e8fa-4a35-bcc8-4897cfd6e1e0.png">

**Comment by rougeth** [comment]
Essa fonte está documentada/disponível em algum lugar?

**Comment by belisarenata** [comment]
Títulos atualizados. Se precisarem correções, favor me marcar.

**Comment by belisarenata** [comment]
Outro detalhe: Alterei o segundo slide, removendo a escrita do plano de fundo e deixando o texto sem a borda. Marquei o slide original como oculto. Se aprovarem a alteração, só apagar o oculto. Senão, apagar o vísivel e desocultar o antigo.

**Comment by belisarenata** [comment]
Pessoal, mais alguma alteração necessária? Posso remover o slide ocultado e encerrar a issue?
