### ISSUE TITLE
Capa para redes sociais

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#42]
### Campanha
Ponta pé inicial
  
### Peça/publicidade solicitada
Capas para redes sociais

### Detalhamento do uso
Capa para as seguintes redes sociais:
- twitter
- facebook
- youtube

### Data prevista para entrega
04 abr. 23

### Quais informações devem aparecer na arte
- logo
- data: 30 out. à 05 nov.
- local: Caxias do Sul
- site: https://2023.pythonbrasil.org.br/

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [x] Outro *(capa para twitter, facebook e youtube)*

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by Buddhamaniac** [comment]
@cecivieira amanhã te entrego o material

**Comment by Buddhamaniac** [comment]
@cecivieira material aqui https://drive.google.com/drive/u/1/folders/1bnPGJ6gYZkQWSbB0P8x6gt-EFaVjtQd_

**Comment by cecivieira** [comment]
@Buddhamaniac Obrigada!

Foram atualizadas as redes sociais
