### ISSUE TITLE
Inserir designer na organização do repositório

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#43]
### Descrição
Inserir Bruno (designer) no repositório do evento.
usuário: [Buddhamaniac](https://github.com/Buddhamaniac)

### Requisitos para a atividade ser considerada como concluída

- Enviar convite
- Pingar ele nos comentários da issue pedindo que aceite o convite

**Comment by rougeth** [comment]
Convite enviado. Pinguei o Bruno no grupo da org no Telegram.

**Comment by cecivieira** [comment]
Pinguei Bruno no whatsapp
