### ISSUE TITLE
Trocar foto de perfil do Flirck

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#45]
### Descrição
Trocar foto de perfil do Flirck.
Minha sugestão é que seja usada a logo genérica:
![image](https://user-images.githubusercontent.com/30605862/229150018-ab249c56-e5a6-42fc-9b49-25ae9bf17337.png)

### Requisitos para a atividade ser considerada como concluída
- Foto de perfil trocada

**Comment by rougeth** [comment]
https://flickr.com/people/pythonbrasil/
