### ISSUE TITLE
Divulgação do plano de patrocínio

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2023-org#47]
### Campanha
Lançamento do evento
  
### Peça/publicidade solicitada
Divulgação do plano de patrocínio em português

### Detalhamento do uso
Incentivar empresas a patrocinarem o evento, bem como incentivar as pessoas da comunidade a enviar o plano de patrocínio dentro da sua empresa.

### Data prevista para entrega
04 abr. 23

### Quais informações devem aparecer na arte
Chamada a ação para patrocinar o evento

### Quais formatos necessários
- [x] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyNE2023)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by cecivieira** [comment]
@Buddhamaniac nova demanda - divulgação de plano de patrocínio

**Comment by Buddhamaniac** [comment]
@cecivieira isso seria um car/post para redes? se sim, quais informações precisam conter nele. Chamada + texto de apoio

**Comment by cecivieira** [comment]
@Buddhamaniac Sim, isso é um card para as redes sociais.

As informaćões que deverão constar na arte são:
Chamada a ação para patrocinar o evento

**Comment by Buddhamaniac** [comment]
@cecivieira mas esse é o texto que vai na arte? pois fica estranho? "Chamada a ação para patrocinar o evento"

Não me parece convidativo. Seria melhor algo"Quer fazer parte da Python 2023? Patrocine o maior evento da américa latina.

O que acha?

**Comment by cecivieira** [comment]
@Buddhamaniac 
Sugestão de texto:
"Quer colaborar para a Python Brasil acontecer? Patrocine o maior evento da américa latina."

**Comment by Buddhamaniac** [comment]
@cecivieira material aqui https://drive.google.com/drive/u/1/folders/14_tYOoNsx8rEe02h7tyh1kM0I_UGDHFO

**Comment by cecivieira** [comment]
@adrianomargarin por favor, revisa as artes. Aguardo teu ok para publicação.
