### ISSUE TITLE
[Reunião] Palestras: 31 de março de 2023

### ISSUE THREAD

**Issue by anadulce** [pythonbrasil/pybr2023-org#48]
# Reunião sobre palestras - 31/03/2023

- Data: 31 de Março de 2023  
- Participantes: 
    - Lucas Eduardo (@Baihanu )
    - Renan de Assis (@renan-assis-santos)
    - Ana Dulce (@anadulce)
    
## Ata

- Copiamos o evento do ano passado como base;
- Definir cronograma de toda a área de conteúdos - (@anadulce fez um esboço a ser aprovado/alterado pela org);
- Definir se teremos palestras em outras línguas;
- Fazer a conta de caracteres do título + nome da pessoa palestrante + sigla da PyBR que caiba no YouTube (@rougeth que manja disso);
- Revisar perguntas - quais perguntas temos, adicionar novas, revisar ordem;
- Revisar as respostas personalizadas das perguntas - aparentemente quando copiamos as perguntas, não foram copiadas as respostas;
- Revisar tamanho dos campos no geral. Os tamanhos foram alterados, mas é necessário um pouquinho de estudo para equilibrar qual o tamanho ideal;
- Diferença entre resumo e descrição - para nós, resumo será exibido nas redes sociais, descrição apenas para avaliação, mas o pretalx exibe ambos na grade. Como não queremos a descrição (que é um conteúdo apenas para avaliação) seja exibido na grade, temos que repensar como fazer isso (por exemplo, criar outro campo para conteúdo voltado para avaliação);
- Criar um vídeo explicando como submeter uma palestra. Dicas de preenchimento, e de como colocar a disponibilidade;
- Definir trilhas: quantas e quais;
- Pagar pretalx antes do lançamento - 336 euros;
- Revisar modelo de avaliação - o modelo atual não é suportado pelo pretalx, aí precisamos fazer algumas contas à parte para ter o ranking oficial;
- Abrir issue pra solicitar artes/conteúdos para o pretalx;
- Fazer um benchmark de como outros eventos usam pretalx (opcional) - https://github.com/pretalx/pretalx/wiki/Events;
### Ações para serem realizadas

- [ ] Definir cronograma de toda a área de conteúdos (@anadulce);
- [x] Definir trilhas: quantas e quais;  (@Baihanu )

**Comment by rougeth** [comment]
Quem vai ficar responsável por "Definir trilhas: quantas e quais;"?

**Comment by rougeth** [comment]
Criei uma issue pra conta do título no YouTube: https://github.com/pythonbrasil/pybr2023-org/issues/49

**Comment by anadulce** [comment]
Quantas trilhas e quais precisa ser definido pela org em reunião. Mais prioritário é saber se aceitaremos submissão em outras línguas.

**Comment by Baihanu** [comment]
> 



> Quantas trilhas e quais precisa ser definido pela org em reunião. Mais prioritário é saber se aceitaremos submissão em outras línguas. @rougeth
Foi definido que haverá inicialmente o aceite de submissão em inglês e espanhol.
