### ISSUE TITLE
Idealizar evento

### ISSUE THREAD

**Issue by lipemorais** [pythonbrasil/pybr2023-org#7]

**Comment by cecivieira** [comment]
Espaço kids

**Comment by cecivieira** [comment]
Intérprete de libras para todas as atividades, incluindo assembleias

**Comment by cecivieira** [comment]
Tendo em vista o local do evento, talvez seja interessante que a transmissão do áudio seja feito por fones individuais para mitigar problema de eco e propagação de som.

**Comment by lipemorais** [comment]
Programa de auxílio para ajuda de custos

**Comment by cecivieira** [comment]
de: Adriano Margarin

[ ] Separação de ingressos de tutoriais e evento principal 
[ ] Gatilhos e escalonamento de tutoriais 
[ ] Cotar estrutura 
[ ] Cotar transmissão por fones
[ ] Estandes de patrocinadores centralizada 
[ ] Carregador de celular em cofre
[ ] Carregador portátil de celular 
[ ] Massagem Quick massage 
[ ] Cadeira de massagem
[ ] Espaço Kids
[ ] Banheiro familia
[ ] Café disponível o dia todo (maquina)
[ ] Música ambiente nos banheiros 
[ ] Open Space soneca
[ ] Achados e perdidos
