### ISSUE TITLE
Inserir Manual de Identidade visual na pasta PyBr2023

### ISSUE THREAD

**Issue by lipemorais** [pythonbrasil/pybr2023-org#8]

**Comment by cecivieira** [comment]
Pasta de destino:
https://drive.google.com/drive/u/0/folders/11wEYmnZYqLrcn3zjflO03xedyZtu61G1

**Comment by cecivieira** [comment]
Feito:

https://drive.google.com/file/d/1mWPqOX9U-m8sOaBS5AOW4L9D4e3P8yjr/view?usp=share_link
