### ISSUE TITLE
Solicitar auxílio PSF

### ISSUE THREAD

**Issue by anadulce** [pythonbrasil/pybr2023-org#98]
A PSF possui um sistema de grants, onde oferece auxílio financeiro para empresas que divulgam a linguagem Python e fomentam a comunidade Python.
Para ser elegível a solicitar este auxílio é necessário preencher alguns pré-requisitos, como ter um local do evento e ingressos à venda.
Mais informações: https://www.python.org/psf/grants/
- [ ] Verificar se o relatório do ano anterior foi enviado (checar com a big kahuna da Python Brasil 2022);

**Comment by anadulce** [comment]
Esta task está bloqueada porque depende do local do evento para solicitação do auxílio da PSF.

**Comment by anadulce** [comment]
Solicitações modelo dos anos anteriores:
https://drive.google.com/file/d/1VAu_iBY2jdQGvQ36bBhzb2seQmJQ3WVr/view?usp=sharing
https://drive.google.com/file/d/1gUrDapMa-ns9_05S8t4ZXcbj_y_4tMpu/view?usp=sharing

**Comment by muriloviana** [comment]
Auxílio aceito ❤️: https://pythonbrasil.freshdesk.com/a/tickets/10414.

Precisamos realizar alguns passos agora:

- [ ] Adicionar logo da PSF no site do evento.
- [ ] Contactar a PSF para adicionar a Python Brasil 2023 no calendário oficial deles.
- [ ] Gerar invoice para PSF.
- [ ] Enviar relatório pós-evento para a PSF.
